### ISSUE TITLE
GUI not showing. Installed in Win 10, RTX 3050

### ISSUE THREAD

**Issue by inra0** [BBC-Esq/VectorDB-Plugin-for-LM-Studio#165]
![webdataset](https://github.com/BBC-Esq/VectorDB-Plugin-for-LM-Studio/assets/32350438/7367f2f2-be53-4ea8-bab9-6dff8ebccf7e)

```
D:\Games\VectorDBllm\src>python gui.py
Traceback (most recent call last):
  File "D:\Games\VectorDBllm\src\gui.py", line 10, in <module>
    from gui_tabs import create_tabs
  File "D:\Games\VectorDBllm\src\gui_tabs.py", line 9, in <module>
    from gui_tabs_database_query import DatabaseQueryTab
  File "D:\Games\VectorDBllm\src\gui_tabs_database_query.py", line 11, in <module>
    from tts_module import BarkAudio, WhisperSpeechAudio
  File "D:\Games\VectorDBllm\src\tts_module.py", line 17, in <module>
    from whisperspeech.pipeline import Pipeline
  File "D:\PY\Lib\site-packages\whisperspeech\pipeline.py", line 12, in <module>
    from whisperspeech import inference, s2a_delar_mup_wds_mlang_cond
  File "D:\PY\Lib\site-packages\whisperspeech\s2a_delar_mup_wds_mlang_cond.py", line 302, in <module>
    from webdataset.filters import default_collation_fn
ModuleNotFoundError: No module named 'webdataset'

D:\Games\VectorDBllm\src>
``` 

I finished the installation, and run python gui.py then failed, as above pic.
Re-run setup.py and still give above ModuleNotFoundError.

**Comment by BBC-Esq** [comment]
Try running this command.  If it works I'll simply need to add it to the requirements.txt file:

```pip install webdataset```
